- packages/public/server/package.json
- packages/public/server/src/module/License/src/License/Controller/LicenseController.php
At the moment the page `/license/add` does look like this:
"Inhalt" is an editor content, which is problematic because you can't enter it in that text-area :D
`/license/update/:id` does this correctly already.
> fix: open editor when adding a license

- packages/public/server/package.json
- packages/public/server/src/module/Ui/src/Ui/View/Helper/Encrypt.php
Replace `mcrypt_encode` and `mcrypt_decode` by `openssl_encode` and `openssl_decode` in the encryption module used for the debugger.
> fix: replace mcrypt by openssl

- packages/public/cloudflare-workers/src/index.ts
- packages/public/server/docker/php/Dockerfile
- packages/public/server/package.json
- packages/public/server/src/config/autoload/global.php
- packages/public/server/src/lang/routes/fr.php
- packages/public/server/src/module/Subject/config/instances.config.php
I added following  https://github.com/serlo/serlo.org/issues/8 the implementation for Serlo-French. I only missed the folder-creation in step 2 (because I have no export-access to crowdin) and in Step 6 the static-assets (serlo.org/public/static-assets). 
Language-code for french: fr_FR
Terms for the image (on the starting-page) in the static-assets: 
democratically structured | structure démocratique
non-profit | non-lucratif
free of charge | gratuit
ad-free | sans publicité
openly licensed | licence libre
transparent | transparent
> Added implementation for Serlo-French (fr.serlo.org)

- packages/private/legacy-editor-to-editor/src/splishToEdtr/convertPlugins.ts
Splish plugin state had a different structure than the new plugin, so the table plugin received an object instead of string.
> Fix: convert tables correctly

- packages/private/edtr-io/src/deserialize.ts
- packages/private/legacy-editor-to-editor/src/index.ts
This fixes #39 taking the first row of the row plugin and use it for content or feedback of the single-/multiple choice plugin
**NOTE**: Might run into problems on some old contents, e.g. when the feedback uses text and images or multiple text blocks.
I also added the `email` and `email_sent` columns to the database (cf. #38)
> Fix: Convert sc-mc content and feedback to text not rows

- packages/public/server/package.json
- packages/public/server/src/module/Ui/templates/entity/view/partials/text-exercise.twig
fix issue introduced in #43 where solutions of sc-mc-exercises by the new editor are not visible
> fix: show solutions in new editor exercises

- packages/private/edtr-io/src/editor.tsx
- packages/private/edtr-io/src/plugins/types/common.tsx
- packages/private/edtr-io/src/plugins/types/course-page.tsx
- packages/private/edtr-io/src/plugins/types/course.tsx
- packages/private/edtr-io/src/plugins/types/text-exercise-group.tsx
- packages/private/edtr-io/src/plugins/types/text-exercise.tsx
- packages/public/client/package.json
- enable exercise specific plugins in text exercise group
- handle invalid course page icons (legacy course pages might have those)
- newly added childs now also are removable.
> Various fixes

- packages/public/server/composer.lock
- packages/public/server/src/module/FeatureFlags/config/module.config.php
- packages/public/server/src/module/FeatureFlags/src/FeatureFlags/Factory/FeatureFlagsHelperFactory.php
- packages/public/server/src/module/FeatureFlags/src/FeatureFlags/Factory/ServiceFactory.php
- packages/public/server/src/module/FeatureFlags/src/FeatureFlags/Service.php
- packages/public/server/src/module/FeatureFlags/src/FeatureFlags/View/Helper/FeatureFlags.php
- packages/public/server/src/module/FeatureFlags/test/FeatureFlagsTest/MockSentry.php
- packages/public/server/src/module/FeatureFlags/test/FeatureFlagsTest/View/Helper/FeatureFlagsTest.php
- yarn.lock
The view helper `featureFlags` can be used in templates. The behavior is a little bit different compared to `FeatureFlags\Service`. E.g., the call
```
$this->featureFlags()->isEnabled('redesign')
```
does the following:
- Check whether there is a query param `featureFlagRedesign`
- Check whether there is a cookie `feature-flags/redesign`
- Check whether `redesign` is enabled via the service (i.e. globally active)
So in templates, you can override the behavior both via query params and cookies
> server: add view helper `featureFlags`

- packages/public/client/package.json
- packages/public/client/src/editor/content/index.ts
- packages/public/client/src/main/index.js
* avoid unintentionally loading editor on #editor elements
* rerender content with new editor after injections (fixes #67)
> Fix: Rerender new editor content in legacy injections

- packages/public/editor-renderer/package.json
- packages/public/editor-renderer/src/index.ts
- packages/public/editor-renderer/src/render.tsx
as a consequence of https://github.com/edtr-io/edtr-io/pull/235 this improves our log messages, because the current handling didn't help much in noticing the issue...
@inyono should we include Sentry-logging there as well?
> improve logging of failed server side renderings

- packages/private/edtr-io/src/plugins.ts
- packages/private/edtr-io/src/plugins/injection.tsx
- packages/public/server/src/module/Entity/src/Entity/Controller/PageController.php
- Use ajax request instead of iframe to fix analytics issues (ref #94)
- Revert: Do not redirect ajax requests - fixes #93
> fix: use ajax request instead of iframe for serlo injections

- packages/public/server/package.json
- packages/public/server/src/module/Ui/src/Ui/View/Helper/DiffHelper.php
- packages/public/server/src/module/Ui/templates/entity/repository/compare-revision.twig
If both fields are legacy format, then the old cleanup of the markdown state is used to create better diffs
> Use legeacy markdown cleanup for diff

- packages/public/server/src/module/Ui/templates/entity/page/course.twig
- packages/public/server/src/module/Ui/templates/entity/view/article.twig
- packages/public/server/src/module/Ui/templates/entity/view/course-page.twig
- packages/public/server/src/module/Ui/templates/entity/view/event.twig
- packages/public/server/src/module/Ui/templates/entity/view/partials/input-challenge.twig
- packages/public/server/src/module/Ui/templates/entity/view/partials/math-puzzle.twig
- packages/public/server/src/module/Ui/templates/entity/view/partials/multiple-choice-answer.twig
- packages/public/server/src/module/Ui/templates/entity/view/partials/single-choice-answer.twig
- packages/public/server/src/module/Ui/templates/entity/view/partials/text-exercise.twig
- packages/public/server/src/module/Ui/templates/entity/view/text-exercise-group.twig
- packages/public/server/src/module/Ui/templates/entity/view/text-hint.twig
- packages/public/server/src/module/Ui/templates/entity/view/text-solution.twig
- packages/public/server/src/module/Ui/templates/page/partials/head.twig
- packages/public/server/src/module/Ui/templates/page/revision/view.twig
Remove legacy HTML attributes for the ory editor introduced in https://github.com/serlo/athene2/commit/717e2373c
> server: Remove legacy HTML attributes (fixes #108)

- package.json
With the --stream option the error output logs of webpack-dev-server are
piped to the lerna output (which is not the case without this option,
see https://github.com/lerna/lerna/issues/449 ). Thus, with this option we see when we
made errors in our scripts or stylesheets.
> yarn: Add --stream to lerna for "start:client"

- packages/public/server/src/module/Ui/templates/static/spenden.phtml
Small fix because of the following request:
> Kann man das Foto auf der Spendenseite kleiner darstellen, habe das Feedback bekommen dass das iritiert wenn das Spendenformular nicht gleich sichtbar ist auf der Seite?
> Smaller main image on donation page

- packages/public/client/src/main/styles/_content.scss
- packages/public/server/src/module/Ui/templates/entity/unrevised.twig
Reverts https://github.com/serlo/serlo.org/commit/914a1a272b61b96a217dfe29d9d951f8c5fb80e8 since it affects to many headings. This needs to be applied to master before the next deployment.
> Fix style of headings

- packages/private/edtr-io/src/plugins/types/common.tsx
- packages/public/client/package.json
- packages/public/server/package.json
- packages/public/server/src/module/Entity/src/Entity/Form/AppletForm.php
- packages/public/server/src/module/Entity/src/Entity/Form/ArticleForm.php
- packages/public/server/src/module/Entity/src/Entity/Form/Element/Changes.php
- packages/public/server/src/module/Entity/src/Entity/Form/EventForm.php
- packages/public/server/src/module/Entity/src/Entity/Form/GroupedTextExerciseForm.php
- packages/public/server/src/module/Entity/src/Entity/Form/InputChallengeForm.php
- packages/public/server/src/module/Entity/src/Entity/Form/MathPuzzleForm.php
- packages/public/server/src/module/Entity/src/Entity/Form/ModuleForm.php
- packages/public/server/src/module/Entity/src/Entity/Form/ModulePageForm.php
- packages/public/server/src/module/Entity/src/Entity/Form/MultipleChoiceRightAnswerForm.php
- packages/public/server/src/module/Entity/src/Entity/Form/MultipleChoiceWrongAnswerForm.php
- packages/public/server/src/module/Entity/src/Entity/Form/SingleChoiceAnswerForm.php
- packages/public/server/src/module/Entity/src/Entity/Form/TextExerciseGroupForm.php
- packages/public/server/src/module/Entity/src/Entity/Form/TextHintForm.php
- packages/public/server/src/module/Entity/src/Entity/Form/TextSolutionForm.php
- packages/public/server/src/module/Entity/src/Entity/Form/VideoForm.php
Fixes #138 
Maybe a follow-up issue:
We have no visual clue for mandatory fields in neither editor... There is a `title` attribute on the disabled "Save" Button, but it's not really obvious that you have to fill in the changes field.
> Make changes a mandatory field

- packages/public/server/src/module/Ui/templates/entity/repository/history.twig
- packages/public/server/src/module/Ui/templates/entity/unrevised.twig
Follow up of #154: `scope=row` for a `<th>` defines a heading for a row  (see https://www.w3.org/TR/html52/tabular-data.html#attr-valuedef-scope-row ) -> I have learned something :smile:
> server: Add scope=row for <th> tags in rows

- packages/public/server/src/module/Entity/src/Entity/Form/AppletForm.php
- packages/public/server/src/module/Entity/test/EntityTest/Form/AppletFormTest.php
- packages/public/server/src/module/Renderer/src/Renderer/View/Helper/RendererHelper.php
- packages/public/server/src/module/Ui/templates/entity/view/applet.twig
All occurrences of ggbm.at are replaced at serlo (there is only one version left which is trashed).
> server: Fix validation of applet urls (fixes #196)

- packages/public/server/src/module/Common/src/Common/Utils.php
- packages/public/server/src/module/Common/test/CommonTest/UtilsTest.php
- packages/public/server/src/module/Entity/src/Entity/Controller/EntityController.php
- packages/public/server/src/module/Entity/src/Entity/Entity/Entity.php
Fixes #237 (and also fixes #167 ) by showing revisions of entities without a subject at `/entity/unrevised`:
This PR is based on #240 which should be merged first.
> Handle entities without subjects at /entity/unrevised

- packages/public/server/src/module/Uuid/src/Uuid/Controller/UuidController.php
- packages/public/server/src/module/Uuid/src/Uuid/Manager/UuidManager.php
- packages/public/server/src/module/Uuid/src/Uuid/Manager/UuidManagerInterface.php
Fixes #229 and closes #193 (after the new purge manager ran once...)
@inyono I want to add some Unit Tests for this before merging, to make sure that the delete logic works as expected.
> fix: clean uuid table after purge to avoid inconsistencies

- packages/public/server/src/module/Uuid/config/module.config.php
- packages/public/server/src/module/Uuid/src/Uuid/Controller/UuidController.php
- packages/public/server/src/module/Uuid/src/Uuid/Manager/UuidManager.php
- packages/public/server/src/module/Uuid/src/Uuid/Manager/UuidManagerInterface.php
Partially fixes #204.
This will filter entities and revisions by language, won't work for other kinds of objects.
TODO: add taxonomies
> Recycle bin: filter by language

- packages/public/server/src/module/Mailman/src/Mailman/Adapter/ZendMailAdapter.php
This PR sets the `Sender` header in send mails. Hopefully it will fix the issue #366.
> server: Set Sender header in emails (#366)

- docker-compose.yml
Not needed after php-cs-fixer got removed. See
https://github.com/serlo/serlo.org/commit/7208ca1a030648a1a27ce7dde803854773fe87d3
> docker php: Remove include of php-cs-fixer config

- packages/public/server/src/module/Ui/templates/entity/page/course.twig
- packages/public/server/src/module/Ui/templates/entity/page/video.twig
- packages/public/server/src/module/Ui/templates/entity/repository/compare-revision.twig
- packages/public/server/src/module/Ui/templates/entity/view/article.twig
- packages/public/server/src/module/Ui/templates/entity/view/course-page.twig
- packages/public/server/src/module/Ui/templates/entity/view/event.twig
- packages/public/server/src/module/Ui/templates/entity/view/partials/input-challenge.twig
- packages/public/server/src/module/Ui/templates/entity/view/partials/math-puzzle.twig
- packages/public/server/src/module/Ui/templates/entity/view/partials/multiple-choice-answer.twig
- packages/public/server/src/module/Ui/templates/entity/view/partials/single-choice-answer.twig
- packages/public/server/src/module/Ui/templates/entity/view/partials/text-exercise.twig
- packages/public/server/src/module/Ui/templates/entity/view/text-exercise-group.twig
- packages/public/server/src/module/Ui/templates/entity/view/text-solution.twig
- packages/public/server/src/module/Ui/templates/layout/1-col.phtml
- packages/public/server/src/module/Ui/templates/layout/2-col.phtml
- packages/public/server/src/module/Ui/templates/layout/3-col.phtml
- packages/public/server/src/module/Ui/templates/layout/partials/footer.phtml
- packages/public/server/src/module/Ui/templates/layout/partials/header.phtml
- packages/public/server/src/module/Ui/templates/layout/partials/right-sidebar.phtml
- packages/public/server/src/module/Ui/templates/page/partials/head.twig
- packages/public/server/src/module/Ui/templates/page/revision/view.twig
Code were included in https://github.com/serlo/athene2/commit/717e2373c027bfa4a35e4dd73aa28dd7bee02f44 but can be removed.
> server: Remove legacy ory code from templates

- packages/public/server/src/module/Subject/config/instances.config.php
Fixes error at a site like https://es.serlo.org/matem%C3%A1ticas/n%C3%BAmeros-y-medidas/divisores-y-n%C3%BAmeros-primos (for authenticated user) which results in error message `An exception has been thrown during the rendering of a template ("Subject "matemáticas" unknown.") in "taxonomy/term/templates/partials/actions" at line 47`
> server: Fix math subject name of Spanish tenant

- packages/public/server/src/module/Ui/templates/layout/default/about-serlo.phtml
fixes #446 
Problem is: the viewBox cuts off the spanish text, so I increased the width of the svg box by 10 to left and right.
Maybe there's also a way to automatically set the viewBox, but this is a quick fix for the issue, until a language has even longer phrases :D
> Quickfix: make viewbox larger for spanish text

- packages/public/server/README.md
- packages/public/server/src/config/autoload/global.php
- packages/public/server/src/config/definitions.local.php
- packages/public/server/src/module/Api/config/module.config.php
- packages/public/server/src/module/Api/src/Controller/UserApiController.php
- packages/public/server/src/module/Api/src/Factory/UserApiControllerFactory.php
- packages/public/server/src/module/Api/test/Controller/ApiControllerTest.php
- packages/public/server/src/module/Api/test/Controller/NavigationApiControllerTest.php
- packages/public/server/src/module/User/src/Factory/UserManagerFactory.php
- packages/public/server/src/module/User/src/Manager/UserManager.php
- packages/public/server/src/module/User/src/Manager/UserManagerInterface.php
- packages/public/server/src/module/User/test/Stub/Manager/UserManagerStub.php
Add the routes `/api/user/active-authors` and `/api/user/active-authors` for accessing the ids for active authors / reviewers.
Links:
* http://en.serlo.localhost:4567/api/user/active-reviewers
* http://en.serlo.localhost:4567/api/user/active-authors
You can change the config [`$mysql_timestamp_for_active_community`](https://github.com/serlo/serlo.org/blob/378f0711909505164a7982b4ab1a8d7fb99a02d4/packages/public/server/src/config/definitions.local.php#L63) for changing the end date of the 90 days period in which the edits / reviews are calculated. You can execute `yarn mysql:import-anonymous-data` and change this value to `CURDATE()` to test the behavior in production. The current values should be similar to
* https://github.com/serlo/serlo.org/blob/master/packages/public/client/src/feature …
> api: Add routes for accessing active community

- packages/public/server/src/module/Api/src/Controller/NavigationApiController.php
- packages/public/server/src/module/Api/test/Controller/NavigationApiControllerTest.php
Fixes https://github.com/serlo/api.serlo.org/issues/76 by ignoring elements in the navigation without an `uri` or `route`.
> server.api: Ignore pages without uri or route

- packages/public/server/__tests-e2e__/api.ts
- packages/public/server/src/module/Api/src/ApiManager.php
- packages/public/server/src/module/Api/src/Controller/ApiController.php
- packages/public/server/src/module/Api/src/Factory/ApiControllerFactory.php
Add support for resolving `/user/profile/:username` in `/api/alias/:alias` so that https://github.com/serlo/api.serlo.org/pull/84 can be finished (see also https://github.com/serlo/api.serlo.org/issues/67 ).
Example result for `http://de.serlo.localhost:4567/api/alias/user/profile/Kulla`:
```json
{
"id": 26217,
"instance": "de",
"path": "/user/profile/Kulla",
"source": "/user/profile/Kulla",
"timestamp": "2014-07-07T18:24:52+02:00"
}
```
> server-api: Add alias support for /user/profile/:username

- packages/public/server/__tests-e2e__/api.ts
- packages/public/server/__tests-e2e__/mails.ts
- packages/public/server/package.json
- yarn.lock
Fixes our e2e tests. unfetch only works in the browser. Thus we need node-fetch
in our e2e tests since they run in Node.js.
> server: Replace "unfetch" with "node-fetch"

- packages/public/server/src/module/Api/src/Manager/NotificationApiManager.php
Needed for https://github.com/serlo/api.serlo.org/issues/92
Here is the only exception, where `objectId` is defined differently:
```php
case 'discussion/create':
return [
'__typename' => 'CreateThreadNotificationEvent',
'actorId' => $event->getActor()->getId(),
'threadId' => $event->getObject()->getId(),
'objectId' => $event->getParameter('on')->getId(),
];
```
> server: Add "objectId" to /api/event/:id

- packages/public/server/__tests-e2e__/_utils.ts
- packages/public/server/__tests-e2e__/entities/static-pages.ts
Replace deprecated function `waitFor()`. Further information see
https://github.com/puppeteer/puppeteer/issues/6214
> server-e2e: Change waitFor() to waitForTimeout()

- packages/public/server/src/module/Entity/src/Controller/EntityController.php
- packages/public/server/src/module/Entity/src/Controller/RepositoryController.php
Closes #553 
This PR implements (ping @elbotho ):
* Adds `#revision-saved` when a revision is saved but needs to be reviewed
* Adds `#revision-accepted` when a revision was successfully checkout out / accepted
* Adds `#revision-rejected` when a revision was successfully rejected
* Adds `#revision-saved-accepted` when a revision was successfully saved and accepted
> Add hash to redirects when storing a revision

- packages/public/server/src/module/Api/src/Controller/ApiController.php
> /api/subscriptions: Return null when user does not exist

- packages/public/server/src/module/Subject/config/instances.config.php
Similarly to the German version where the topic "Methodenkiste" got renamed to "Lerntipps", we decided to rename "Boite a methodes" to "conseils pour apprendre".
> Renamed topic "boite a methodes" to "conseils pour apprendre" 

- packages/public/server/src/module/Api/config/module.config.php
- packages/public/server/src/module/Api/src/ApiManager.php
- packages/public/server/src/module/Api/src/Controller/GraphQLMockController.php
- packages/public/server/src/module/Api/src/Factory/ApiManagerFactory.php
- packages/public/server/src/module/Api/src/Factory/GraphQLMockControllerFactory.php
- packages/public/server/src/module/Api/src/Factory/GraphQLMockStorageFactory.php
- packages/public/server/src/module/Api/src/Manager/NotificationApiManager.php
- packages/public/server/src/module/Api/src/Service/AbstractGraphQLService.php
- packages/public/server/src/module/Api/src/Service/GraphQLMockService.php
- packages/public/server/src/module/Api/src/Service/GraphQLService.php
- packages/public/server/src/module/Authentication/src/Storage/UserSessionStorageInterface.php
- packages/public/server/src/module/Authentication/test/Stub/Service/AuthenticationServiceStub.php
- packages/public/server/src/module/Ui/templates/authentication/login.phtml
- packages/public/server/src/module/User/test/Stub/Entity/UserStub.php
Adds `/graphql/list` and `/graphql/clear` to inspect the outgoing GraphQL requests locally. Behaves the same as `/mails/list` and `/mails/clear`:
- `/graphql/list` lists the timestamp, query, and variables for the any outgoing GraphQL request.
- `/graphql/clear` clears that list.
This should help debug issues like #605 and also enables the possibility of e2e tests for listeners.
> server(api): add GraphQLMockService

- packages/public/server/src/module/Api/src/Listener/LinkServiceListener.php
The parent on a link change needs to be updated when the uuid is newly
created. Otherwise for example the course is not updated when a new
course page is created or an exercise is not updated when a solution is
added.
> listener: Update parent for newly created uuid

- packages/public/server/src/module/Api/src/ApiManager.php
- packages/public/server/src/module/Api/src/Listener/LinkServiceListener.php
- packages/public/server/src/module/Api/src/Service/AbstractGraphQLService.php
- packages/public/server/src/module/Entity/src/Controller/LinkController.php
- packages/public/server/src/module/Link/src/Service/LinkService.php
This fixes an error when the children of an entity are ordered in the local environment since the new site cannot be rendered.
When the order of course pages are changed by the following tool
there is an error displayed clicking the "save" button:
Currently after changing the order with the POST request there is a redirect to the new course page https://github.com/serlo/serlo.org/blob/7e75da6d79ba04f1d592dec6e73ae3d4c1d52d82/packages/public/server/src/module/Entity/src/Controller/LinkController.php#L50-L83 However the new course page cannot be displayed since the following error occurs 
The fix is to not redirect to the new course but to return a success immediately.
> Fix error when entity children are ordered

- packages/public/server/src/module/Entity/src/Controller/EntityController.php
- packages/public/server/src/module/Entity/src/Manager/EntityManager.php
- packages/public/server/src/module/Entity/src/Manager/EntityManagerInterface.php
Fixes the current bug that there revisions missing in `/entity/unrevised`
Also closes https://github.com/serlo/serlo.org/issues/626
> Fix: revisions are not shown at /entity/unrevised

- packages/public/server/docker/php/php.ini-custom
Closes https://github.com/serlo/serlo.org/issues/649
Since PHP 5.39 there is the configutation max_input_vars (
https://www.php.net/manual/en/info.configuration.php#ini.max-input-vars
) which limits the amount of input variables. Since the page
`/entity/taxonomy/update/:id` sends a variable per term this number was
exceeded and the sended variables after 1000 were cut off. Thus after
the 1000th term no new assignments could be saved.
> Increase max_input_vars

- packages/private/edtr-io/src/plugins/equations/editor.tsx
- packages/public/client/package.json
This PR includes two things:
* When a new line is added with the `tab` shortcut the previous explanation instead of the left statement gets focus
* Fixes a bug in chrome that for a new equation element both the left statement and the explanation have focus. Entering a character in this state would move the cursor from the left field to the explanation
Due to the severity of the bug I would like to include this before the other improvements.
> Fix bug in chrome with equations plugin

- packages/private/edtr-io/package.json
- packages/private/edtr-io/src/plugins/types/text-exercise-group.tsx
- packages/private/edtr-io/src/plugins/types/text-solution.tsx
- yarn.lock
Legacy port of Frontend PR: https://github.com/serlo/frontend/pull/1359
Our implementation of react-virtual currently isn't working (All elements are rendered anyway) and causing some UI issues (Not listening to dimension changes by spoilers, misplacing the plugin overlay). Easiest solution for now is to just revert #656 which this PR does.
Long-term we might want to wait for https://github.com/tannerlinsley/react-virtual/pull/80 or implement one of the solutions mentioned there.
> edtr-io: remove react-virtual
