.gitattributes
packages/private/workspace-image/Dockerfile
packages/public/notifications-job/Dockerfile
packages/public/notifications-job/package.json
packages/public/notifications-job/scripts/deploy.ts
packages/public/notifications-job/src/index.ts
packages/public/server/package.json
packages/public/server/src/module/Event/src/Event/EventManager.php
packages/public/server/src/module/Notification/Module.php
packages/public/server/src/module/Notification/config/module.config.php
packages/public/server/src/module/Notification/src/Notification/Controller/WorkerController.php
packages/public/server/src/module/Notification/src/Notification/Entity/Notification.php
packages/public/server/src/module/Notification/src/Notification/Entity/NotificationInterface.php
packages/public/server/src/module/Notification/src/Notification/Listener/EventManagerListener.php
packages/public/server/src/module/Notification/src/Notification/NotificationManager.php
packages/public/server/src/module/Notification/src/Notification/NotificationManagerInterface.php
packages/public/server/src/module/Notification/src/Notification/NotificationWorker.php
yarn.lock

Refactor notification handling

---

packages/public/server/src/module/Entity/src/Entity/Controller/RepositoryController.php

- check for changes in revisions correctly
- handle save of entity without previous revision

fix: check for changes correctly

---

packages/public/client/package.json
packages/public/editor-renderer/package.json
packages/public/server/package.json

new release for server, client and editor-renderer

chore: increment version

---

packages/public/server/package.json
packages/public/server/src/module/Newsletter/src/Newsletter/Listener/UserControllerListener.php
packages/public/server/src/module/Ui/templates/user/user/register.twig
packages/public/server/src/module/User/src/User/Controller/UserController.php
packages/public/server/src/module/User/src/User/Entity/Field.php
packages/public/server/src/module/User/src/User/Entity/User.php
packages/public/server/src/module/User/src/User/Entity/UserInterface.php
packages/public/server/src/module/User/src/User/Form/Register.php
packages/public/server/src/module/User/src/User/Form/RegisterFilter.php
packages/public/server/src/module/User/src/User/Manager/UserManager.php
packages/public/server/src/module/User/src/User/Manager/UserManagerInterface.php

add table for user fields and save interests on registration

---

packages/public/cloudflare-workers/src/index.ts

Should be merged after https://github.com/serlo/infrastructure-env-production/pull/3 got applied **DO NOT MERGE BEFORE PLZ :)**

cloudflare-workers: remove proxy

---

packages/public/server/package.json
packages/public/server/src/module/Authentication/src/Authentication/Controller/HydraController.php
packages/public/server/src/module/Authentication/src/Authentication/Factory/HydraControllerFactory.php

- Automatically accept login challenge if user is logged
- Login user to serlo.org, when oauth login challenge successfull

Improve integration of oauth with our authentication system

---

packages/public/frontend/src/footer/about.tsx
packages/public/frontend/src/footer/nav.tsx

removing conflicts with bootstrap styles

fixing footer styles

---

packages/public/frontend/package.json
packages/public/frontend/pages/_document.js
packages/public/frontend/patch/next/dist/client/index.js
packages/public/frontend/patch/next/dist/client/index.tsx

**serlo.org / frontend**
- use component-only logic also in development server mode

hot module reloading for frontend server

---

packages/public/server/src/module/Page/src/Page/Controller/IndexController.php

server: Reverse order of revisions for static pages

---

packages/public/server/package.json
packages/public/server/src/module/Entity/src/Entity/Entity/Entity.php

hotfix: show unrevised revisions of subentities

---

packages/private/edtr-io/package.json
packages/private/edtr-io/src/deserialize.ts
packages/private/edtr-io/src/plugins/types/applet.tsx
packages/private/edtr-io/src/plugins/types/article.tsx
packages/private/edtr-io/src/plugins/types/common.tsx
packages/private/edtr-io/src/plugins/types/course-page.tsx
packages/private/edtr-io/src/plugins/types/course.tsx
packages/private/edtr-io/src/plugins/types/event.tsx
packages/private/edtr-io/src/plugins/types/helpers/settings.tsx
packages/private/edtr-io/src/plugins/types/math-puzzle.tsx
packages/private/edtr-io/src/plugins/types/text-exercise-group.tsx
packages/private/edtr-io/src/plugins/types/text-exercise.tsx
packages/private/edtr-io/src/plugins/types/text-hint.tsx
packages/private/edtr-io/src/plugins/types/text-solution.tsx
packages/private/edtr-io/src/plugins/types/video.tsx
packages/public/server/src/module/Entity/config/route.config.php
packages/public/server/src/module/Entity/src/Entity/Controller/RepositoryController.php
packages/public/server/src/module/Ui/src/Ui/View/Helper/Timeago.php

add button to switch to older revisions

---

README.md
package.json

I needed this command often for #166 -> thus I added it to `package.json`

yarn: Add "mysql" command

---

package.json
packages/public/server/package.json
packages/public/server/src/module/Subject/config/instances.config.php

Supersedes #169 because there were format issues and I can't push to @jakobwes fork.

 Added two topics in other language-versions, #160

---

jest.config-ssr.js
packages/private/edtr-io/src/plugins.ts
yarn.lock

hotifx for #165: use HighlightPlugin

hotfix: use highlightPlugin

---

jest.config-e2e.js
jest.setup-e2e.js
jest.setup-e2e.ts
packages/public/server/__tests-e2e__/_config.ts
packages/public/server/__tests-e2e__/_utils.ts
packages/public/server/__tests-e2e__/entities/event.ts
packages/public/server/__tests-e2e__/entities/grouped-exercise.ts
packages/public/server/__tests-e2e__/entities/grouped-text-exercise.ts
packages/public/server/__tests-e2e__/entities/math-puzzle.ts
packages/public/server/__tests-e2e__/entities/video.ts
packages/public/server/__tests-e2e__/home.ts
packages/public/server/__tests-e2e__/mails.ts
packages/public/server/src/module/Ui/templates/entity/page/event.twig
packages/public/server/src/module/Ui/templates/entity/page/math-puzzle.twig
packages/public/server/src/module/Ui/templates/entity/page/video.twig
packages/public/server/src/module/Ui/templates/entity/view/event.twig
packages/public/server/src/module/Ui/templates/entity/view/video.twig

Improvements for e2e testing

---

packages/public/server/src/module/Entity/config/module.config.php
packages/public/server/src/module/Entity/src/Entity/Controller/EntityController.php
packages/public/server/src/module/Entity/src/Entity/Factory/EntityControllerFactory.php
packages/public/server/src/module/Ui/templates/entity/unrevised.twig

I worked together with @yolo-bird He whiches to have a list of help link directly on the new page `/entity/unrevised`:

server: Add helper links for reviewing

---

packages/public/client/src/main/modules/donation-banner.tsx

Maybe this does help distinguishing network problems from other bugs in sentry...

catch failing ajax requests

---

packages/public/frontend/next.config.js

multi-pass of terser is breaking existing code

fixing incorrect minifier

---

packages/private/edtr-io/src/plugins/types/video.tsx
packages/public/client/package.json
packages/public/editor-renderer/package.json
packages/public/frontend/package.json
packages/public/frontend/src/edtr-io/plugins/types/video.tsx
packages/public/server/package.json

Edtr-io: Fix video state type

---

packages/public/client/src/frontend/modules/injections.js
packages/public/frontend/package.json
packages/public/frontend/pages/__editor.tsx
packages/public/frontend/patch/next/dist/client/index.js
packages/public/frontend/patch/next/dist/client/index.tsx
packages/public/frontend/src/edtr-io/plugins/injection.tsx

running nextjs hydration process again after injection is loaded

fix broken injections

---

packages/public/server/src/module/Entity/config/route.config.php
packages/public/server/src/module/Entity/src/Entity/Controller/ApiController.php

Adds http://de.serlo.localhost:4567/entities/are-we-edtr-io-yet. Gonna expose a simple UI for that via Cloudflare Worker.

server: add api route to get stats about converted entities

---

packages/public/server/src/module/Ui/templates/static/spenden.phtml

sever: Update donation page after contact person changed (fixes #243)

---

packages/public/server/src/module/Ui/templates/entity/page/default.twig
packages/public/server/src/module/Ui/templates/entity/view/course.twig
packages/public/server/src/module/Ui/templates/entity/view/default.twig
packages/public/server/src/module/Ui/templates/entity/view/toc/default.twig

Fix #260 empty course has no ui

---

packages/public/client/src/main/modules/diff/overrides.css

Little improvement for the diff view:

server: Wrap lines in diff view (#103)

---

packages/public/server/src/module/Ui/templates/static/spenden.phtml

server: Update donation page (#fixes 332)

---

packages/public/client/src/frontend/styles/base/_typography.scss
packages/public/server/src/module/Ui/templates/discussion/helper/default/discussion.twig
packages/public/server/src/module/Ui/templates/entity/unrevised.twig
packages/public/server/src/module/User/src/User/Factory/UserHelperFactory.php
packages/public/server/src/module/User/src/User/View/Helper/UserHelper.php

Fixes #311 Fixes #310 Fixes #309 
What is a newbie? -> at most 5 edits and comments combined
How is it highlighted? -> * (open for discussion)

Highlight newbies in revision and discussion overview

---

packages/public/client/src/frontend/styles/partials/_serlo_consent_banner.scss

client: Fix consent banner hiding toolbar (Fixes #47)

---

jest.setup-e2e.ts
packages/public/server/__tests-e2e__/_utils.ts
packages/public/server/__tests-e2e__/entities/applet.ts
packages/public/server/__tests-e2e__/entities/article.ts
packages/public/server/__tests-e2e__/entities/course.ts
packages/public/server/__tests-e2e__/entities/exercise.ts
packages/public/server/__tests-e2e__/entities/video.ts
packages/public/server/__tests-e2e__/taxonomy.ts

Server: Fix i18n in e2e-tests

---

packages/public/server/README.md
packages/public/server/src/config/autoload/global.php
packages/public/server/src/config/autoload/production.php
packages/public/server/src/config/definitions.local.php
packages/public/server/src/module/Common/src/Utils.php
packages/public/server/src/module/Common/test/UtilsTest.php
packages/public/server/src/module/Entity/config/module.config.php
packages/public/server/src/module/Entity/src/Controller/RepositoryController.php
packages/public/server/src/module/Entity/src/Entity/Entity.php
packages/public/server/src/module/Entity/src/Entity/EntityInterface.php
packages/public/server/src/module/Entity/src/Factory/EntityControllerFactory.php
packages/public/server/src/module/Entity/src/Factory/RepositoryControllerFactory.php
packages/public/server/src/module/Taxonomy/src/Entity/TaxonomyTerm.php
packages/public/server/src/module/Taxonomy/src/Entity/TaxonomyTermInterface.php
packages/public/server/src/module/Versioning/src/Factory/RepositoryManagerFactory.php
packages/public/server/src/module/Versioning/src/RepositoryManager.php
packages/public/server/src/module/Versioning/src/RepositoryManagerInterface.php

Fixes #312 
~*Unhold*: There seems to be a discussion in the issue whether we want to have it.~

Add autoreview in predefined taxonomy terms

---

packages/public/server/__tests-e2e__/taxonomy.ts
packages/public/server/src/module/Versioning/src/Factory/RepositoryManagerFactory.php

autoreview: Catch TermNotFoundException (fixes #447)

---

packages/public/server/src/module/Taxonomy/src/Controller/TermController.php
packages/public/server/src/module/Taxonomy/src/Manager/TaxonomyManager.php
packages/public/server/src/module/Taxonomy/src/Manager/TaxonomyManagerInterface.php

Fixes https://github.com/serlo/api.serlo.org/issues/72

Api update on taxonomy order

---

packages/public/server/src/module/Api/src/Controller/ApiController.php
packages/public/server/src/module/User/src/Manager/UserManagerInterface.php
packages/public/server/src/module/User/test/Stub/Manager/UserManagerStub.php

Follow up of #502: Fixes https://github.com/serlo/serlo.org/pull/502#discussion_r502261868

server-api-alias: Use regex to match username

---

packages/public/client/__tests__/input-challenge.js
packages/public/client/package.json
packages/public/client/src/frontend/modules/input_challenge.js

* Refactoring of `__tests__/input-challenge.js`
* Remove the dependency of the package `string` since this package is not under active development (and it is only rarely used)
* Ignore `+` sign in front of number ( #493 )

Improvements for the input challenge

---

packages/public/server/src/module/Api/src/ApiManager.php

Supplement of https://github.com/serlo/api.serlo.org/pull/87 for fixing https://github.com/serlo/api.serlo.org/issues/73

server-api-uuid: Add field "revisionIds"

---

packages/public/server/__tests-e2e__/api.ts
packages/public/server/src/module/Api/config/module.config.php
packages/public/server/src/module/Api/src/Controller/ApiController.php
packages/public/server/src/module/Api/src/Factory/ApiControllerFactory.php

server-api: Add /api/subscriptions/:userId

---

packages/public/client/package.json
packages/public/client/src/feature-prototypes/index.ts
packages/public/client/src/feature-prototypes/teacher-survey-banner.ts

Adds banner to current teacher survey:
Requirements:
1. Banner shall only be visible at de.serlo.org
2. Banner shall only be visible on desktops (big screens)
3. Banner shall only be visible until Saturday
4. Banner shall not be visible during school time (Mo-Fr 8-12)
5. Banner shall not be visible for authenticated user
6. Banner shall not be visible after 4min it was first shown
7. Banner shall not be visible at start page and pages for authentication / registering

client: Add banner to survey for teachers

---

packages/public/client/src/feature-prototypes/teacher-survey-banner.ts
packages/public/client/src/modules/analytics.ts

There shall be a new campaign for the teacher banner until this Sunday with a bigger banner. Also events shall be tracked with simpleanalytics (how often is the banner shown, shown to individual users and clicked):

New Campaign: Teacher survey banner

---

packages/public/client/src/modules/analytics.ts

The code of simpleanalytics has a bug - this is a temporary workaround.

client: Fix bug in simpleanalytics for sending events

---

packages/private/edtr-io/src/plugins/table.tsx
packages/private/mathjax/package.json
packages/private/mathjax/src/index.ts
packages/public/client/package.json
packages/public/client/src/legacy-editor/index.js
packages/public/client/src/legacy-editor/legacy-content/index.ts
packages/public/editor-renderer/package.json

edtr-io: enable MathJax for tables

---

packages/public/server/package.json
packages/public/server/src/module/Alias/src/AliasManager.php
packages/public/server/src/module/Alias/src/Controller/AliasController.php
packages/public/server/src/module/Api/config/module.config.php
packages/public/server/src/module/Api/src/ApiManager.php
packages/public/server/src/module/Api/src/Controller/ApiController.php
packages/public/server/src/module/Api/src/Factory/ApiControllerFactory.php
packages/public/server/src/module/Api/src/Factory/ApiManagerFactory.php
packages/public/server/src/module/Api/src/Factory/DiscussionManagerListenerFactory.php
packages/public/server/src/module/Api/src/Factory/SubscriptionManagerListenerFactory.php
packages/public/server/src/module/Api/src/Listener/DiscussionManagerListener.php
packages/public/server/src/module/Api/src/Listener/RepositoryManagerListener.php
packages/public/server/src/module/Api/src/Listener/SubscriptionManagerListener.php
packages/public/server/src/module/Api/src/Module.php
packages/public/server/src/module/Discussion/src/Entity/Comment.php
packages/public/server/src/module/Entity/src/Manager/EntityManager.php
packages/public/server/src/module/Notification/src/SubscriptionManager.php
packages/public/server/src/module/Uuid/src/Manager/UuidManagerInterface.php

Add additional API listeners

---

packages/public/server/src/module/Alias/src/AliasManager.php
packages/public/server/src/module/Common/src/Filter/Shortify.php
packages/public/server/src/module/Common/src/Filter/Slugify.php
packages/public/server/src/module/Term/src/Entity/TermEntity.php

* Shorten code in AliasManager
* Make filter function in Shortify and Slugify short
* Remove unnused import in TermEntity

server: Shorten code in AliasManager and its filters

---

packages/public/server/src/module/Alias/src/AliasManager.php
packages/public/server/src/module/Alias/src/AliasManagerInterface.php
packages/public/server/src/module/Alias/src/Controller/AliasController.php
packages/public/server/src/module/Alias/src/Factory/AliasControllerFactory.php
packages/public/server/src/module/Alias/src/Factory/AliasManagerFactory.php
packages/public/server/src/module/Api/src/ApiManager.php
packages/public/server/src/module/Api/src/Controller/ApiController.php

server: handle router routes correctly when resolving alias

---

packages/migrations/package.json
packages/migrations/scripts/build.ts
packages/migrations/src/20201218151642-remove-splish-states.ts
packages/migrations/yarn.lock
packages/public/server/package.json

Close https://github.com/serlo/frontend/issues/704

migrations: migrate remaining Splish Editor states to Edtr.io states

---

packages/public/server/src/config/definitions.local.php

So I do not forget the configuration again :-)

server: Document how to set api_options properly

---

packages/public/server/src/module/Taxonomy/src/Controller/TermController.php

Closes https://github.com/serlo/serlo.org/issues/560

server: Update api cache for parent when term is created

---

packages/public/server/src/module/Entity/src/Controller/EntityController.php

See https://community.serlo.org/channel/global-admin-requests?msg=CyiWTDaxsojyoTvit018794:

server: Change guideline link for reviewers

---

packages/private/edtr-io/src/plugins/types/common.tsx

Closes https://github.com/serlo/serlo.org/issues/565 (Quick fix)
https://github.com/edtr-io/edtr-io/pull/336 has a reason why and a possible fix which we can discuss there

edtr-io: Make redo button always visible

---

packages/private/edtr-io/src/plugins/injection.tsx
packages/public/client/package.json
packages/public/client/src/editor/editor/index.tsx

For https://github.com/serlo/serlo.org-cloudflare-worker/issues/181 and https://github.com/serlo/serlo.org-cloudflare-worker/pull/187

Set X-From to legacy-serlo.org for AJAX requests

---

packages/public/server/src/module/Entity/src/Controller/EntityController.php

Closes https://github.com/serlo/serlo.org/issues/616

Remove link to Rocket Chat in /entity/unrevised

---

packages/public/server/src/module/Api/src/ApiManager.php
packages/public/server/src/module/Api/src/Listener/LinkServiceListener.php
packages/public/server/src/module/Api/src/Service/AbstractGraphQLService.php
packages/public/server/src/module/Link/src/Service/LinkService.php

Fixes https://github.com/serlo/serlo.org/issues/620

fix: Add listener when order of entity children is changed

---

packages/public/server/package.json
packages/public/server/src/module/Discussion/src/DiscussionManager.php

Fix discussion listeners

---

packages/public/server/src/module/Api/src/Listener/NotificationManagerListener.php
packages/public/server/src/module/Api/src/Manager/NotificationApiManager.php
yarn.lock

Notification listeners

---

packages/public/server/package.json
packages/public/server/src/module/Alias/src/AliasManager.php

Fix alias of entity revisions

---

packages/public/server/src/config/instance/navigation/default.php
packages/public/server/src/module/User/config/module.config.php
packages/public/server/src/module/User/src/Controller/UserController.php

Follow up of https://github.com/serlo/serlo.org-cloudflare-worker/pull/209 with which the route /user/public can never be reached.

Remove route /user/public

---

packages/public/server/package.json
packages/public/server/src/module/Api/src/Listener/LicenseManagerListener.php
packages/public/server/src/module/Api/src/Listener/LinkServiceListener.php
packages/public/server/src/module/Api/src/Listener/RepositoryManagerListener.php
packages/public/server/src/module/Api/src/Listener/TaxonomyManagerListener.php
packages/public/server/src/module/Api/src/Listener/UuidManagerListener.php

Closes https://github.com/serlo/serlo.org/issues/657

API: Remove cache instead of updating it

---

packages/public/server/src/module/Api/src/ApiManager.php
packages/public/server/src/module/Api/src/Listener/SubscriptionManagerListener.php

Closes https://github.com/serlo/serlo.org/issues/669

API: Remove subscriptions instead of setting it

---

packages/migrations/dist/20210923155000-add-first-explanation-to-equation.js
packages/migrations/package.json
packages/migrations/src/20210923155000-add-first-explanation-to-equation.ts
packages/migrations/src/utils/create-migration.ts
packages/migrations/src/utils/edtr-io.ts
packages/migrations/yarn.lock

@inyono Please have a detailed look since it is my first DB migration...

Add migration for first-explanation of equations

---

packages/migrations/dist/20211101205000-move-physics-to-subjects-under-construction.js
packages/migrations/src/20211101205000-move-physics-to-subjects-under-construction.ts

See https://community.serlo.org/channel/physik?msg=gSZs4pQ4nLTKFAt5J

Add migration for moving physics to "subjects under construction"

---

packages/public/server/src/module/Normalizer/src/View/Helper/Normalize.php

for #651
any objections?
is that a bad idea? :D

noindex for legacy

---

packages/public/server/src/module/Api/src/Service/AbstractGraphQLService.php

See https://github.com/serlo/api.serlo.org/issues/687

api: Use "keys" instead of "key" in removeCache()
